### ISSUE TITLE
Is Table 3 wrong?

### ISSUE THREAD

**Issue by ameame666** [Haiyang-W/TokenFormer#12]
For TokenFormer, the parameters for the QKV Proj and Output Proj in Table 3 are given as n_layer * d_token * n. However, these Pattention layers have both Key and Value parameter tokens. The parameters for the FFN are 2 * n_layer * d_token * d_ff. In the provided code, the FFN in the Transformer is replaced by one Pattention layer, and I think *2 indicates that there are two sets of parameter tokens. Therefore, is 2 * n_layer * d_token * n the correct parameter count for the QKV Proj and Output Proj?

**Comment by yuyunwen** [comment]
please see this link https://openreview.net/forum?id=oQ4igHyh3N

**Comment by ameame666** [comment]
> please see this link https://openreview.net/forum?id=oQ4igHyh3N

OK, many thanks.
