### ISSUE TITLE
What is the difference between pattention and FFN?

### ISSUE THREAD

**Issue by sufubao** [Haiyang-W/TokenFormer#13]
If we regard the K parameter as ```gate_up_proj``` without bias and the V parameter as ```down_proj``` without bias, then what is the difference between Pattention and FFN?

**Comment by kroggen** [comment]
1. softmax or similar instead of simple non-linearity, will retrieve keys that are similar to the query
2. ability to grow, add more empty K/V parameters

**Comment by klutzydrummer** [comment]
> If we regard the K parameter as ```gate_up_proj``` without bias and the V parameter as ```down_proj``` without bias, then what is the difference between Pattention and FFN?

As far as I can gather, there is no effective difference. The point of the tokenformer architecture is that the weights for that operation are dynamically retrieved at inference instead of being a static set of weights that are always assigned to that position.
